version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: kaiburrdb
    volumes:
      - mongo_data:/data/db

  springboot-app:
    build: .
    container_name: task-api
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/kaiburrdb

volumes:
  mongo_data:
